api_version: 1
auto_merge:
  - dependency: govuk_schemas
    allowed_semver_bumps:
      - patch
      - minor
  - dependency: plek
    allowed_semver_bumps:
      - patch
      - minor
  - dependency: rubocop-govuk
    allowed_semver_bumps:
      - patch
      - minor
